// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7j83iAjcIZ6G9IUpq2bBUWdZQL9_Lahs',
    appId: '1:497190154492:web:7ac727677bfe4992e76779',
    messagingSenderId: '497190154492',
    projectId: 'swello-w',
    authDomain: 'swello-w.firebaseapp.com',
    databaseURL: 'https://swello-w.firebaseio.com',
    storageBucket: 'swello-w.appspot.com',
    measurementId: 'G-K31YW32B68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdSXm6cnzD8vA35JoCAnPpZjJdVC7CKw0',
    appId: '1:497190154492:android:9aa708204e65c2ede76779',
    messagingSenderId: '497190154492',
    projectId: 'swello-w',
    databaseURL: 'https://swello-w.firebaseio.com',
    storageBucket: 'swello-w.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQe3WnHHqvMIzZa9OA6_ZxY7W9s8pSx6k',
    appId: '1:497190154492:ios:efae3cc096caf193e76779',
    messagingSenderId: '497190154492',
    projectId: 'swello-w',
    databaseURL: 'https://swello-w.firebaseio.com',
    storageBucket: 'swello-w.appspot.com',
    androidClientId: '497190154492-m9r9j5sd9e6oe3glh6rfoiqdo5j5m0dj.apps.googleusercontent.com',
    iosClientId: '497190154492-9tqh7cq2c271hjorete1o6hpicvo3cht.apps.googleusercontent.com',
    iosBundleId: 'com.swello.kids.cardgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQe3WnHHqvMIzZa9OA6_ZxY7W9s8pSx6k',
    appId: '1:497190154492:ios:efae3cc096caf193e76779',
    messagingSenderId: '497190154492',
    projectId: 'swello-w',
    databaseURL: 'https://swello-w.firebaseio.com',
    storageBucket: 'swello-w.appspot.com',
    androidClientId: '497190154492-m9r9j5sd9e6oe3glh6rfoiqdo5j5m0dj.apps.googleusercontent.com',
    iosClientId: '497190154492-9tqh7cq2c271hjorete1o6hpicvo3cht.apps.googleusercontent.com',
    iosBundleId: 'com.swello.kids.cardgame',
  );
}
